export const limit = 10;

// using url without / at the start because base url ends with /
const ENDPOINTS = {
  LOGIN: "user/signin",
  SIGNOUT: "user/signout",
  INVITE_PARTNER: "partner/invite",
  VERIFY_PARTNER_TOKEN: (userId: string) => `user/${userId}/verify-token`,
  ACCOUNT_SETUP: "partner/account-setup",
  CURRENT_USER: "user",
  UPDATE_PASSWORD: "user/update-password",
  GET_PARTNER: (id: string) => `partner/${id}`,
  UPLOAD_IMAGE: "upload-image",
  GET_RESOURCES: `resource`,
  GET_PARTNERS: `partner`,
  GET_ENGAGEMENTS: (resourceId: string) => `resource/${resourceId}/engagement`,
  PUT_PARTNER_ACCOUNT_SETTINGS: (id: string) => `partner/${id}`,
  RESET_PASSWORD: (userId: string) => `user/${userId}/reset-password`,
  DASHBOARD_DATA_ADMIN: `admin/dashboard-data`,
  DASHBOARD_DATA: (id: string) => `partner/${id}/dashboard-data`,
  PATCH_RESOURCE_STATUS: (id: string) => `resource/${id}/status`,
  PATCH_PARTNER_STATUS: (id: string) => `partner/${id}/status`,
  UPLOAD_RESUME: "upload-resume",
  PUT_RESOURCE: (id: string) => `resource/${id}`,
  POST_EXPERIENCE: (id: string) => `resource/${id}/experience`,
  POST_SKILL: (id: string) => `resource/${id}/skill`,
  GET_SKILL: `skill`,
  POST_EDUCATION: (id: string) => `resource/${id}/education`,
  GET_FAVOURITE_RESOURCE: `end-user/favorite-resource`,
  GET_BOOKED_RESOURCE: `end-user/booked-resource`,
  GET_PROJECT: `project`,
  PUT_PROJECT: (id: string) => `project/${id}`,
  END_USERS: `end-users`,
  TIME_SLOT: (id: string) => `resource/${id}/time-slots`,
  TIME_SLOT_DETAILS: (id: string) => `resource/${id}/configurations`,
  TIMEZONES: `https://timeapi.io/api/timezone/availabletimezones`,
  READ_MESSAGES: (id: string) => `inquiry/${id}/read-messages`,
  GET_MESSAGES: (id: string) => `inquiry/${id}/messages`,
  SEND_MESSAGE: (id: string) => `inquiry/${id}/send-message`,
  INQUIRES: `inquiry`,
  INTERVIEW: `schedule-interview`,
  TIMESHEET: (engagementId: string) => `engagement/${engagementId}/timesheet`,
  TIMESHEET_BY_ID: (timesheetId: string) => `timesheet/${timesheetId}`,
  TIMESHEETREVISION: (timesheetId: string) =>
    `timesheet/${timesheetId}/revision`,
  INVOICE: `invoice`,
  INVOICE_BY_ID: (invoiceId: string) => `invoice/${invoiceId}`,
  PATCH_INVOICE: (invoiceId: string) => `invoice/${invoiceId}/payout-status`,
  PARTNER_INVOICE_ACTION: (invoiceId: string) => `invoice/${invoiceId}/partner-action`,
  DASHBOARD_TIMESHEET_LISTING: (id: string) => `timesheet/${id}/partner`,
  DASHBOARD_RESOURCE_HOURS_DATA: (id: string) =>
    `partner/${id}/dashboard-data/resource-hours`,
  DASHBOARD_REVENUE_DATA: (id: string) =>
    `partner/${id}/dashboard-data/revenue`,
  DASHBOARD_REVENUE_DATA_ADMIN: `admin/dashboard-data/revenue`,
  FORGOT_PASSWORD: `user/forgot-password`,
  ALL_ENGAGEMENTS: () => `engagement`,
  PATCH_ENGAGEMENTS: (id: string) => `engagement/${id}/status`,
  INVITE_END_USER: `end-user/invite`,
};

export default ENDPOINTS;
