export enum ROUTES {
  LOGIN = "/login",
  REGISTER = "/sign-up",
  PROFILE = "/profile-setup",
  DASHBOARD = "/dashboard",
  ADMINRESOURCE = "/:id",
  CREATERESOURCE = "resources/create-new-resource",
  CREATEADMINRESOURCE = "resources/:id",
  SETTINGS = "account",
  RESOURCES = "/dashboard/resources",
  RESOURCE_PROFILE = "resources/:id",
  RESOURCE_PROFILE_REPLACE = "/dashboard/resources/:id",
  INTERVIEWS = "interviews",
  INTERVIEWLISTING = "/interviews",
  TIMESHEET = "timesheets",
  TIMESHEET_BY_ID = "timesheets/:id",
  VIEW_TIMESHEET = "/dashboard/resources/:id/engagements/timesheets",
  VIEW_TIMESHEET_ENGAGEMENT = "/dashboard/engagements/timesheets",
  VIEW_ENGAGEMENTS = "/dashboard/resources/:id/engagements",
  VIEW_TIMESHEET_BY_ID = "/dashboard/resources/:id/engagements/timesheets/:timeId",
  VIEW_TIMESHEET_BY_ID_ENGAGMENTS = "/dashboard/engagements/timesheets/:timeId",
  INVOICE_BY_ID = "/dashboard/invoices/:id",
  INVOICES = "/dashboard/invoices",
  FORGOT_PASSWORD = "/forgot-password",
  INQUIRES = "/dashboard/inquiries",
  // more routes will be added here
}
