export enum PrivateRoutes {
  DASHBOARD = "/dashboard",
  RESOURCES = "/dashboard/resources",
  ACCOUNT = "/dashboard/account",
  CREATERESOURCE = "/dashboard/resources/create-new-resource",
  CREATEPARTNERRESOURCE = "/dashboard/partners/:id/resources/create-new-resource",
  VIEWRESOURCEBYIDADMIN = "/dashboard/resources/:id/engagements",
  EDITRESOURCEBYIDADMIN = "/dashboard/resources/:id",
  EDITPARTNERBYID = "/dashboard/partners/:id",
  VIEWRESOURCEBYID = "/dashboard/resources/:id",
  EDITRESOURCEBYID = "/dashboard/resources/:id/edit",
  PARTNERRESOURCES = "/dashboard/partners/:id/resources",
  PARTNERRESOURCESENGAGEMENTS = "/dashboard/partners/:id/resources/:j",
  PROJECTSBYUSER = "/dashboard/project/:id",
  PROJECT = "/dashboard/project",
  CREATEPROJECT = "/dashboard/project/create",
  RESOURCE_PROFILE = "/dashboard/resources/:id",
  EDIT_RESOURCE_PROFILE = "/dashboard/resources/:id/edit",
  ADMIN_PARTNER_RESOURCE_PROFILE = "/dashboard/partners/:i/resources/:j",
  ADMIN_PARTNER_RESOURCE_PROFILE_VIEW_ENGAGEMENTS = "/dashboard/partners/:i/resources/:j/engagements",
}
